"""Generate TypeScript contracts from canonical JSON Schemas."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "generated" / "typescript" / "factory.ts"
CONTEXT_RESEARCH_OUTPUT = ROOT / "generated" / "typescript" / "context-research.ts"


def load(relative_path: str) -> dict:
    return json.loads((ROOT / relative_path).read_text(encoding="utf-8"))


def union(values: list[str]) -> str:
    return " | ".join(json.dumps(value) for value in values)


def render() -> str:
    request = load("schemas/factory/factory-analyze-request.schema.json")
    response = load("schemas/factory/factory-analyze-response.schema.json")
    catalog = load("schemas/factory/capability-catalog-item.schema.json")
    resolution = load("schemas/factory/capability-decision.schema.json")
    capability = load("schemas/capability/capability-draft.schema.json")
    detail = load("schemas/capability/capability-detail.schema.json")
    requirement = load("schemas/factory/requirement.schema.json")
    requirement_understanding = load(
        "schemas/factory/requirement-understanding.schema.json"
    )

    capability = load("schemas/capability/capability-draft.schema.json")
    detail = load("schemas/capability/capability-detail.schema.json")

    capability_types = request["properties"]["preferred_capability_type"]["enum"]
    decisions = response["properties"]["decision"]["enum"]
    risks = capability["properties"]["risk_level"]["enum"]
    availability = catalog["properties"]["availability"]["enum"]
    configuration = catalog["properties"]["configuration_status"]["enum"]
    readiness = resolution["properties"]["activation_readiness"]["enum"]

    return rf'''// Generated by scripts/generate_typescript.py. DO NOT EDIT.
// Source of truth: alos-contracts JSON Schemas and public OpenAPI.

export const FACTORY_ANALYZE_PATH = "/api/v1/genesis/factory/analyze" as const;
export const CAPABILITY_DETAIL_PATH = "/api/v1/capabilities" as const;

export type CapabilityType = {union(capability_types)};
export type FactoryDecision = {union(decisions)};
export type RiskLevel = {union(risks)};
export type CapabilityAvailability = {union(availability)};
export type CapabilityConfigurationStatus = {union(configuration)};
export type ActivationReadiness = {union(readiness)};

export interface FactoryAnalyzeRequest {{
  readonly requirement: string;
  readonly preferred_capability_type?: CapabilityType;
}}

export interface CapabilityCatalogItem {{
  readonly capability_id: string;
  readonly version: string;
  readonly name: string;
  readonly purpose: string;
  readonly capability_type: CapabilityType;
  readonly risk_level: RiskLevel;
  readonly availability: CapabilityAvailability;
  readonly configuration_status: CapabilityConfigurationStatus;
  readonly backing_tool_ids: readonly string[];
  readonly permission_refs: readonly string[];
  readonly scope_refs: readonly string[];
  readonly keywords?: readonly string[];
}}

export interface CapabilityDraft {{
  readonly tenant_id: string;
  readonly organization_id: string;
  readonly workspace_id: string;
  readonly correlation_id: string;
  readonly capability_id: string;
  readonly version: string;
  readonly name: string;
  readonly purpose: string;
  readonly owner: string;
  readonly capability_type: CapabilityType;
  readonly output_state: "DRAFT";
  readonly lifecycle_state: "DRAFT";
  readonly scope_refs: readonly string[];
  readonly tool_ids: readonly string[];
  readonly permission_refs: readonly string[];
  readonly prohibited_actions: readonly string[];
  readonly risk_level: RiskLevel;
  readonly evidence_requirements: readonly string[];
  readonly test_requirements: readonly string[];
  readonly constraints?: readonly string[];
  readonly human_gate_required?: boolean;
  readonly dependency_refs?: readonly string[];
}}

export type CapabilityLifecycleState = "DRAFT" | "APPROVED" | "ACTIVE" | "SUSPENDED" | "RETIRED";

export interface CapabilityDetail {{
  readonly capability_id: string;
  readonly version: string;
  readonly name: string;
  readonly purpose: string;
  readonly owner: string;
  readonly capability_type: CapabilityType;
  readonly lifecycle_state: CapabilityLifecycleState;
  readonly risk_level: RiskLevel;
  readonly availability: CapabilityAvailability;
  readonly configuration_status: CapabilityConfigurationStatus;
  readonly scope_refs: readonly string[];
  readonly permission_refs: readonly string[];
  readonly backing_tool_ids: readonly string[];
  readonly prohibited_actions: readonly string[];
  readonly evidence_requirements: readonly string[];
  readonly test_requirements: readonly string[];
  readonly constraints?: readonly string[];
  readonly dependency_refs?: readonly string[];
  readonly human_gate_required: boolean;
  readonly decision_id?: string;
  readonly release_id?: string;
  readonly created_by: string;
  readonly correlation_id: string;
  readonly created_at: string;
}}

export interface AgentDraft {{
  readonly draft_id: string;
  readonly tenant_id: string;
  readonly organization_id: string;
  readonly workspace_id: string;
  readonly correlation_id: string;
  readonly agent_id: string;
  readonly version: string;
  readonly purpose: string;
  readonly capability_type: "AGENT";
  readonly scope_refs: readonly string[];
  readonly tool_ids: readonly string[];
  readonly permission_refs: readonly string[];
  readonly prohibited_actions: readonly string[];
  readonly risk_level: RiskLevel;
  readonly evidence_requirements: readonly string[];
  readonly test_requirements: readonly string[];
  readonly lifecycle_state: "DRAFT";
  readonly agent_definition: Readonly<Record<string, unknown>>;
}}

export interface RegistryDraftReference {{
  readonly subject_type: "CAPABILITY" | "AGENT";
  readonly identifier: string;
  readonly version: string;
  readonly state: "DRAFT";
}}

export interface RegistryDraftResult {{
  readonly state: "DRAFT";
  readonly registered_refs: readonly RegistryDraftReference[];
}}

export interface FactoryAnalyzeResponse {{
  readonly correlation_id: string;
  readonly decision: FactoryDecision;
  readonly reason: string;
  readonly existing_capability_refs: readonly CapabilityCatalogItem[];
  readonly capability_draft: CapabilityDraft | null;
  readonly agent_draft: AgentDraft | null;
  readonly registry_result: RegistryDraftResult | null;
}}

export interface ContractError {{
  readonly code: string;
  readonly message: string;
  readonly details?: Readonly<Record<string, unknown>>;
  readonly correlation_id: string;
  readonly retryable: boolean;
}}

export class AlosContractError extends Error {{
  readonly problem: ContractError;

  constructor(problem: ContractError) {{
    super(problem.message);
    this.name = "AlosContractError";
    this.problem = problem;
  }}
}}

export async function analyzeFactory(
  baseUrl: string,
  request: FactoryAnalyzeRequest,
  init: Omit<RequestInit, "body" | "method"> = {{}},
  fetcher: typeof fetch = fetch,
): Promise<FactoryAnalyzeResponse> {{
  const response = await fetcher(`${{baseUrl.replace(/\/$/, "")}}${{FACTORY_ANALYZE_PATH}}`, {{
    ...init,
    method: "POST",
    headers: {{
      Accept: "application/json",
      "Content-Type": "application/json",
      ...init.headers,
    }},
    body: JSON.stringify(request),
  }});
  const payload: unknown = await response.json();
  if (!response.ok) throw new AlosContractError(payload as ContractError);
  return payload as FactoryAnalyzeResponse;
}}

export async function getCapabilityDetail(
  baseUrl: string,
  capabilityId: string,
  init: Omit<RequestInit, "body" | "method"> = {{}},
  fetcher: typeof fetch = fetch,
): Promise<CapabilityDetail> {{
  const response = await fetcher(
    `${{baseUrl.replace(/\/$/, "")}}${{CAPABILITY_DETAIL_PATH}}/${{encodeURIComponent(capabilityId)}}`,
    {{
      ...init,
      method: "GET",
      headers: {{
        Accept: "application/json",
        ...init.headers,
      }},
    }},
  );
  const payload: unknown = await response.json();
  if (!response.ok) throw new AlosContractError(payload as ContractError);
  return payload as CapabilityDetail;
}}
'''


def render_context_research() -> str:
    execution_context = load("schemas/common/execution-context.schema.json")
    source_semantics = load("schemas/common/source-semantics.schema.json")
    evidence = load("schemas/evidence/evidence-ref.schema.json")
    research_decision = load("schemas/research/research-decision.schema.json")
    context_projection = load("schemas/context/context-projection.schema.json")
    domain_access = load("schemas/research/domain-access-response.schema.json")
    research_request = load("schemas/research/public-research-request.schema.json")
    research_receipt = load("schemas/research/research-request-receipt.schema.json")

    classifications = load("schemas/common/data-classification.schema.json")["enum"]
    authority_levels = execution_context["properties"]["authority_context"]["properties"][
        "authority_level"
    ]["enum"]
    source_types = source_semantics["$defs"]["source_type"]["enum"]
    reliability = source_semantics["$defs"]["source_reliability"]["enum"]
    freshness = source_semantics["$defs"]["freshness_status"]["enum"]
    trust = source_semantics["$defs"]["content_trust"]["enum"]
    validation = evidence["properties"]["validation_status"]["enum"]
    decisions = research_decision["properties"]["decision"]["enum"]
    domains = research_decision["properties"]["domain"]["enum"]
    context_states = context_projection["properties"]["status"]["enum"]
    domain_access_states = domain_access["properties"]["domains"]["items"]["properties"][
        "status"
    ]["enum"]
    source_modes = research_request["properties"]["source_mode"]["enum"]
    receipt_states = research_receipt["properties"]["state"]["enum"]

    return rf'''// Generated by scripts/generate_typescript.py. DO NOT EDIT.
// Shared context, evidence, and research contract types. They carry data and grant no authority.

export const CONTEXT_OPTIONS_PATH = "/api/v1/genesis/context-options" as const;
export const RESEARCH_DOMAIN_ACCESS_PATH = "/api/v1/research/domain-access" as const;
export const RESEARCH_REQUEST_PATH = "/api/v1/research/requests" as const;

export type DataClassification = {union(classifications)};
export type AuthorityLevel = {union(authority_levels)};
export type SourceType = {union(source_types)};
export type SourceReliability = {union(reliability)};
export type FreshnessStatus = {union(freshness)};
export type ContentTrust = {union(trust)};
export type EvidenceValidationStatus = {union(validation)};
export type ResearchDecisionKind = {union(decisions)};
export type ResearchDomain = {union(domains)};
export type ContextLifecycleState = {union(context_states)};
export type ResearchDomainAccessStatus = {union(domain_access_states)};
export type ResearchSourceMode = {union(source_modes)};
export type ResearchRequestState = {union(receipt_states)};

export interface ExecutionBudget {{
  readonly max_tokens?: number;
  readonly max_cost?: number;
  readonly max_steps?: number;
  readonly max_tool_calls?: number;
  readonly max_children?: number;
  readonly max_depth?: number;
  readonly timeout_seconds?: number;
  readonly concurrency_limit?: number;
}}

export interface AuthorityContext {{
  readonly role: string;
  readonly role_refs?: readonly string[];
  readonly authority_level?: AuthorityLevel;
}}

export interface ExecutionContext {{
  readonly tenant_id: string;
  readonly organization_id: string;
  readonly workspace_id: string;
  readonly actor_id: string;
  readonly authority_context: AuthorityContext;
  readonly permission_refs?: readonly string[];
  readonly allowed_tool_ids?: readonly string[];
  readonly scope_refs: readonly string[];
  readonly data_classification: DataClassification;
  readonly correlation_id: string;
  readonly execution_budget?: ExecutionBudget;
}}

export interface EvidenceRef {{
  readonly tenant_id?: string;
  readonly organization_id?: string;
  readonly workspace_id?: string;
  readonly run_id?: string;
  readonly correlation_id?: string;
  readonly scope_refs?: readonly string[];
  readonly evidence_id: string;
  readonly source_id: string;
  readonly uri: string;
  readonly captured_at: string;
  readonly retrieved_at?: string;
  readonly content_hash: string;
  readonly source_version?: string;
  readonly anchor?: string;
  readonly excerpt?: string;
  readonly data_classification?: DataClassification;
  readonly source_type?: SourceType;
  readonly freshness?: FreshnessStatus;
  readonly reliability?: SourceReliability;
  readonly content_trust?: ContentTrust;
  readonly instruction_authority?: false;
  readonly validation_status?: EvidenceValidationStatus;
  readonly metadata?: Readonly<Record<string, unknown>>;
}}

export interface EvidenceBundle {{
  readonly bundle_id: string;
  readonly tenant_id: string;
  readonly organization_id: string;
  readonly workspace_id: string;
  readonly run_id: string;
  readonly correlation_id: string;
  readonly scope_refs?: readonly string[];
  readonly evidence_refs: readonly EvidenceRef[];
}}

export interface ContextItem {{
  readonly key: string;
  readonly value: unknown;
  readonly source_id: string;
  readonly evidence_id: string;
  readonly source_version: string;
  readonly content_hash: string;
  readonly anchor: string;
  readonly data_classification: DataClassification;
  readonly source_type?: SourceType;
  readonly freshness?: FreshnessStatus;
  readonly reliability?: SourceReliability;
  readonly content_trust?: ContentTrust;
  readonly instruction_authority?: false;
}}

export interface ContextBundle {{
  readonly context_id: string;
  readonly tenant_id: string;
  readonly organization_id: string;
  readonly workspace_id: string;
  readonly actor_id: string;
  readonly correlation_id: string;
  readonly goal?: string;
  readonly capability_id?: string;
  readonly allowed_tool_ids?: readonly string[];
  readonly execution_budget?: ExecutionBudget;
  readonly memory_refs?: readonly string[];
  readonly created_at: string;
  readonly expires_at?: string;
  readonly scope_refs: readonly string[];
  readonly items: readonly ContextItem[];
  readonly evidence_refs?: readonly EvidenceRef[];
}}

export interface ContextProjection {{
  readonly status: ContextLifecycleState;
  readonly context_id?: string;
  readonly tenant_id?: string;
  readonly organization_id?: string;
  readonly workspace_id?: string;
  readonly actor_id?: string;
  readonly goal?: string;
  readonly capability_id?: string;
  readonly data_classification?: DataClassification;
  readonly scope_refs?: readonly string[];
  readonly evidence_refs?: readonly EvidenceRef[];
  readonly items?: readonly ContextItem[];
  readonly needs_info_reason?: string;
  readonly denial_reason?: string;
  readonly correlation_id: string;
}}

export interface BackendRetrievalProposal {{
  readonly boundary: "BACKEND_TOOL_EXECUTOR";
  readonly tool_id: string;
  readonly instruction_authority: false;
  readonly permission_expansion: false;
  readonly scope_expansion: false;
}}

export interface ResearchDecision {{
  readonly research_id?: string;
  readonly run_id?: string;
  readonly correlation_id: string;
  readonly decision: ResearchDecisionKind;
  readonly domain: ResearchDomain;
  readonly selected_evidence_ids: readonly string[];
  readonly reasons: readonly string[];
  readonly retrieval?: BackendRetrievalProposal | null;
  readonly external_content_trust: "UNTRUSTED";
}}

export interface ResearchDomainAccessRecord {{
  readonly domain: ResearchDomain;
  readonly status: ResearchDomainAccessStatus;
  readonly is_allowed: boolean;
  readonly reason: string;
  readonly required_scope?: string;
}}

export interface ResearchDomainAccessResponse {{
  readonly domains: readonly ResearchDomainAccessRecord[];
  readonly correlation_id: string;
}}

export interface ResearchRequest {{
  readonly question: string;
  readonly source_mode: ResearchSourceMode;
  readonly domain: ResearchDomain;
}}

export interface ResearchRequestReceipt {{
  readonly request_id: string;
  readonly state: ResearchRequestState;
  readonly correlation_id: string;
  readonly decision: ResearchDecisionKind;
}}
'''


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    expected_context_research = render_context_research()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != expected:
            raise SystemExit("generated/typescript/factory.ts is stale; run the generator")
        if (
            not CONTEXT_RESEARCH_OUTPUT.exists()
            or CONTEXT_RESEARCH_OUTPUT.read_text(encoding="utf-8")
            != expected_context_research
        ):
            raise SystemExit(
                "generated/typescript/context-research.ts is stale; run the generator"
            )
        print(f"Verified {OUTPUT.relative_to(ROOT)}")
        print(f"Verified {CONTEXT_RESEARCH_OUTPUT.relative_to(ROOT)}")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(expected, encoding="utf-8", newline="\n")
    CONTEXT_RESEARCH_OUTPUT.write_text(
        expected_context_research, encoding="utf-8", newline="\n"
    )
    print(f"Generated {OUTPUT.relative_to(ROOT)}")
    print(f"Generated {CONTEXT_RESEARCH_OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
