"""Generate dependency-free Python contract types from canonical schemas."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "generated" / "python" / "context_research_contracts.py"


def load(relative_path: str) -> dict:
    return json.loads((ROOT / relative_path).read_text(encoding="utf-8"))


def literal(values: list[str]) -> str:
    return "Literal[" + ", ".join(repr(value) for value in values) + "]"


def render() -> str:
    execution_context = load("schemas/common/execution-context.schema.json")
    source_semantics = load("schemas/common/source-semantics.schema.json")
    evidence = load("schemas/evidence/evidence-ref.schema.json")
    decision = load("schemas/research/research-decision.schema.json")

    classifications = load("schemas/common/data-classification.schema.json")["enum"]
    authority_levels = execution_context["properties"]["authority_context"]["properties"][
        "authority_level"
    ]["enum"]
    source_types = source_semantics["$defs"]["source_type"]["enum"]
    reliability = source_semantics["$defs"]["source_reliability"]["enum"]
    freshness = source_semantics["$defs"]["freshness_status"]["enum"]
    trust = source_semantics["$defs"]["content_trust"]["enum"]
    validation = evidence["properties"]["validation_status"]["enum"]
    decisions = decision["properties"]["decision"]["enum"]
    domains = decision["properties"]["domain"]["enum"]

    return f'''# Generated by scripts/generate_python.py. DO NOT EDIT.
# Shared context, evidence, and research contract types. These declarations carry data and grant no authority.

from typing import Literal, Required, TypedDict

DataClassification = {literal(classifications)}
AuthorityLevel = {literal(authority_levels)}
SourceType = {literal(source_types)}
SourceReliability = {literal(reliability)}
FreshnessStatus = {literal(freshness)}
ContentTrust = {literal(trust)}
EvidenceValidationStatus = {literal(validation)}
ResearchDecisionKind = {literal(decisions)}
ResearchDomain = {literal(domains)}


class ExecutionBudget(TypedDict, total=False):
    max_tokens: int
    max_cost: float
    max_steps: int
    max_tool_calls: int
    max_children: int
    max_depth: int
    timeout_seconds: int
    concurrency_limit: int


class AuthorityContext(TypedDict, total=False):
    role: Required[str]
    role_refs: list[str]
    authority_level: AuthorityLevel


class ExecutionContext(TypedDict, total=False):
    tenant_id: Required[str]
    organization_id: Required[str]
    workspace_id: Required[str]
    actor_id: Required[str]
    authority_context: Required[AuthorityContext]
    permission_refs: list[str]
    allowed_tool_ids: list[str]
    scope_refs: Required[list[str]]
    data_classification: Required[DataClassification]
    correlation_id: Required[str]
    execution_budget: ExecutionBudget


class EvidenceRef(TypedDict, total=False):
    tenant_id: str
    organization_id: str
    workspace_id: str
    run_id: str
    correlation_id: str
    scope_refs: list[str]
    evidence_id: Required[str]
    source_id: Required[str]
    uri: Required[str]
    captured_at: Required[str]
    retrieved_at: str
    content_hash: Required[str]
    source_version: str
    anchor: str
    excerpt: str
    data_classification: DataClassification
    source_type: SourceType
    freshness: FreshnessStatus
    reliability: SourceReliability
    content_trust: ContentTrust
    instruction_authority: Literal[False]
    validation_status: EvidenceValidationStatus
    metadata: dict[str, object]


class EvidenceBundle(TypedDict, total=False):
    bundle_id: Required[str]
    tenant_id: Required[str]
    organization_id: Required[str]
    workspace_id: Required[str]
    run_id: Required[str]
    correlation_id: Required[str]
    scope_refs: list[str]
    evidence_refs: Required[list[EvidenceRef]]


class ContextItem(TypedDict, total=False):
    key: Required[str]
    value: Required[object]
    source_id: Required[str]
    evidence_id: Required[str]
    source_version: Required[str]
    content_hash: Required[str]
    anchor: Required[str]
    data_classification: Required[DataClassification]
    source_type: SourceType
    freshness: FreshnessStatus
    reliability: SourceReliability
    content_trust: ContentTrust
    instruction_authority: Literal[False]


class ContextBundle(TypedDict, total=False):
    context_id: Required[str]
    tenant_id: Required[str]
    organization_id: Required[str]
    workspace_id: Required[str]
    actor_id: Required[str]
    correlation_id: Required[str]
    goal: str
    capability_id: str
    allowed_tool_ids: list[str]
    execution_budget: ExecutionBudget
    memory_refs: list[str]
    created_at: Required[str]
    expires_at: str
    scope_refs: Required[list[str]]
    items: Required[list[ContextItem]]
    evidence_refs: list[EvidenceRef]


class BackendRetrievalProposal(TypedDict):
    boundary: Literal['BACKEND_TOOL_EXECUTOR']
    tool_id: str
    instruction_authority: Literal[False]
    permission_expansion: Literal[False]
    scope_expansion: Literal[False]


class ResearchDecision(TypedDict, total=False):
    research_id: str
    run_id: str
    correlation_id: Required[str]
    decision: Required[ResearchDecisionKind]
    domain: Required[ResearchDomain]
    selected_evidence_ids: Required[list[str]]
    reasons: Required[list[str]]
    retrieval: BackendRetrievalProposal | None
    external_content_trust: Required[Literal['UNTRUSTED']]
'''


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != expected:
            raise SystemExit(
                "generated/python/context_research_contracts.py is stale; run the generator"
            )
        print(f"Verified {OUTPUT.relative_to(ROOT)}")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(expected, encoding="utf-8", newline="\n")
    print(f"Generated {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
