"""Generate dependency-free Python contract types from canonical schemas."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "generated" / "python" / "context_research_contracts.py"
SKILLS_OUTPUT = ROOT / "generated" / "python" / "skill_contracts.py"


def load(relative_path: str) -> dict:
    return json.loads((ROOT / relative_path).read_text(encoding="utf-8"))


def literal(values: list[str]) -> str:
    return "Literal[" + ", ".join(repr(value) for value in values) + "]"


def render() -> str:
    execution_context = load("schemas/common/execution-context.schema.json")
    source_semantics = load("schemas/common/source-semantics.schema.json")
    evidence = load("schemas/evidence/evidence-ref.schema.json")
    decision = load("schemas/research/research-decision.schema.json")
    context_projection = load("schemas/context/context-projection.schema.json")
    domain_access = load("schemas/research/domain-access-response.schema.json")
    research_request = load("schemas/research/public-research-request.schema.json")
    research_receipt = load("schemas/research/research-request-receipt.schema.json")

    classifications = load("schemas/common/data-classification.schema.json")["enum"]
    authority_levels = execution_context["properties"]["authority_context"]["properties"][
        "authority_level"
    ]["enum"]
    source_types = source_semantics["$defs"]["source_type"]["enum"]
    reliability = source_semantics["$defs"]["source_reliability"]["enum"]
    freshness = source_semantics["$defs"]["freshness_status"]["enum"]
    trust = source_semantics["$defs"]["content_trust"]["enum"]
    validation = evidence["properties"]["validation_status"]["enum"]
    decisions = decision["properties"]["decision"]["enum"]
    domains = decision["properties"]["domain"]["enum"]
    context_states = context_projection["properties"]["status"]["enum"]
    domain_access_states = domain_access["properties"]["domains"]["items"]["properties"][
        "status"
    ]["enum"]
    source_modes = research_request["properties"]["source_mode"]["enum"]
    receipt_states = research_receipt["properties"]["state"]["enum"]

    return f'''# Generated by scripts/generate_python.py. DO NOT EDIT.
# Shared context, evidence, and research contract types. These declarations carry data and grant no authority.

from typing import Literal, Required, TypedDict

DataClassification = {literal(classifications)}
AuthorityLevel = {literal(authority_levels)}
SourceType = {literal(source_types)}
SourceReliability = {literal(reliability)}
FreshnessStatus = {literal(freshness)}
ContentTrust = {literal(trust)}
EvidenceValidationStatus = {literal(validation)}
ResearchDecisionKind = {literal(decisions)}
ResearchDomain = {literal(domains)}
ContextLifecycleState = {literal(context_states)}
ResearchDomainAccessStatus = {literal(domain_access_states)}
ResearchSourceMode = {literal(source_modes)}
ResearchRequestState = {literal(receipt_states)}


class ExecutionBudget(TypedDict, total=False):
    max_tokens: int
    max_cost: float
    max_steps: int
    max_tool_calls: int
    max_children: int
    max_depth: int
    timeout_seconds: int
    concurrency_limit: int


class AuthorityContext(TypedDict, total=False):
    role: Required[str]
    role_refs: list[str]
    authority_level: AuthorityLevel


class ExecutionContext(TypedDict, total=False):
    tenant_id: Required[str]
    organization_id: Required[str]
    workspace_id: Required[str]
    actor_id: Required[str]
    authority_context: Required[AuthorityContext]
    permission_refs: list[str]
    allowed_tool_ids: list[str]
    scope_refs: Required[list[str]]
    data_classification: Required[DataClassification]
    correlation_id: Required[str]
    execution_budget: ExecutionBudget


class EvidenceRef(TypedDict, total=False):
    tenant_id: str
    organization_id: str
    workspace_id: str
    run_id: str
    correlation_id: str
    scope_refs: list[str]
    evidence_id: Required[str]
    source_id: Required[str]
    uri: Required[str]
    captured_at: Required[str]
    retrieved_at: str
    content_hash: Required[str]
    source_version: str
    anchor: str
    excerpt: str
    data_classification: DataClassification
    source_type: SourceType
    freshness: FreshnessStatus
    reliability: SourceReliability
    content_trust: ContentTrust
    instruction_authority: Literal[False]
    validation_status: EvidenceValidationStatus
    metadata: dict[str, object]


class EvidenceBundle(TypedDict, total=False):
    bundle_id: Required[str]
    tenant_id: Required[str]
    organization_id: Required[str]
    workspace_id: Required[str]
    run_id: Required[str]
    correlation_id: Required[str]
    scope_refs: list[str]
    evidence_refs: Required[list[EvidenceRef]]


class ContextItem(TypedDict, total=False):
    key: Required[str]
    value: Required[object]
    source_id: Required[str]
    evidence_id: Required[str]
    source_version: Required[str]
    content_hash: Required[str]
    anchor: Required[str]
    data_classification: Required[DataClassification]
    source_type: SourceType
    freshness: FreshnessStatus
    reliability: SourceReliability
    content_trust: ContentTrust
    instruction_authority: Literal[False]


class ContextBundle(TypedDict, total=False):
    context_id: Required[str]
    tenant_id: Required[str]
    organization_id: Required[str]
    workspace_id: Required[str]
    actor_id: Required[str]
    correlation_id: Required[str]
    goal: str
    capability_id: str
    allowed_tool_ids: list[str]
    execution_budget: ExecutionBudget
    memory_refs: list[str]
    created_at: Required[str]
    expires_at: str
    scope_refs: Required[list[str]]
    items: Required[list[ContextItem]]
    evidence_refs: list[EvidenceRef]


class ContextProjection(TypedDict, total=False):
    status: Required[ContextLifecycleState]
    context_id: str
    tenant_id: str
    organization_id: str
    workspace_id: str
    actor_id: str
    goal: str
    capability_id: str
    data_classification: DataClassification
    scope_refs: list[str]
    evidence_refs: list[EvidenceRef]
    items: list[ContextItem]
    needs_info_reason: str
    denial_reason: str
    correlation_id: Required[str]


class BackendRetrievalProposal(TypedDict):
    boundary: Literal['BACKEND_TOOL_EXECUTOR']
    tool_id: str
    instruction_authority: Literal[False]
    permission_expansion: Literal[False]
    scope_expansion: Literal[False]


class ResearchDecision(TypedDict, total=False):
    research_id: str
    run_id: str
    correlation_id: Required[str]
    decision: Required[ResearchDecisionKind]
    domain: Required[ResearchDomain]
    selected_evidence_ids: Required[list[str]]
    reasons: Required[list[str]]
    retrieval: BackendRetrievalProposal | None
    external_content_trust: Required[Literal['UNTRUSTED']]


class ResearchDomainAccessRecord(TypedDict, total=False):
    domain: Required[ResearchDomain]
    status: Required[ResearchDomainAccessStatus]
    is_allowed: Required[bool]
    reason: Required[str]
    required_scope: str


class ResearchDomainAccessResponse(TypedDict):
    domains: list[ResearchDomainAccessRecord]
    correlation_id: str


class ResearchRequest(TypedDict):
    question: str
    source_mode: ResearchSourceMode
    domain: ResearchDomain


class ResearchRequestReceipt(TypedDict):
    request_id: str
    state: ResearchRequestState
    correlation_id: str
    decision: ResearchDecisionKind
'''


def render_skills() -> str:
    return '''# Generated by scripts/generate_python.py. DO NOT EDIT.
# Skill references and declarations carry prerequisites, never authority grants.

from typing import Literal, NotRequired, Required, TypedDict

SkillLifecycleState = Literal["DRAFT", "APPROVED", "ACTIVE", "SUSPENDED", "RETIRED"]
SkillRiskLevel = Literal["LOW", "MEDIUM", "HIGH", "CRITICAL"]

class SkillRef(TypedDict):
    skill_id: str
    skill_version: str

class SkillDefinition(SkillRef, total=False):
    name: Required[str]
    description: Required[str]
    purpose: str
    when_to_use: list[str]
    input_schema_ref: Required[str]
    output_schema_ref: Required[str]
    procedure: list[str]
    tool_ids: list[str]
    required_tool_ids: list[str]
    permission_refs: list[str]
    scope_refs: list[str]
    owner_actor_id: str
    risk_level: SkillRiskLevel

class AgentSkillAssignmentRequest(SkillRef):
    agent_id: str
    agent_version: str
    proposed_agent_version: NotRequired[str]

class AgentSkillAssignmentReceipt(TypedDict):
    agent_id: str
    base_agent_version: str
    draft_agent_version: str
    skill_ref: SkillRef
    lifecycle_state: Literal["DRAFT"]
    correlation_id: str
'''


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    expected_skills = render_skills()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != expected:
            raise SystemExit(
                "generated/python/context_research_contracts.py is stale; run the generator"
            )
        print(f"Verified {OUTPUT.relative_to(ROOT)}")
        if not SKILLS_OUTPUT.exists() or SKILLS_OUTPUT.read_text(encoding="utf-8") != expected_skills:
            raise SystemExit("generated/python/skill_contracts.py is stale; run the generator")
        print(f"Verified {SKILLS_OUTPUT.relative_to(ROOT)}")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(expected, encoding="utf-8", newline="\n")
    SKILLS_OUTPUT.write_text(expected_skills, encoding="utf-8", newline="\n")
    print(f"Generated {OUTPUT.relative_to(ROOT)}")
    print(f"Generated {SKILLS_OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
