"""Generate the H1 public Factory TypeScript contract from canonical JSON Schemas."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "generated" / "typescript" / "factory.ts"


def load(relative_path: str) -> dict:
    return json.loads((ROOT / relative_path).read_text(encoding="utf-8"))


def union(values: list[str]) -> str:
    return " | ".join(json.dumps(value) for value in values)


def render() -> str:
    request = load("schemas/factory/factory-analyze-request.schema.json")
    response = load("schemas/factory/factory-analyze-response.schema.json")
    catalog = load("schemas/factory/capability-catalog-item.schema.json")
    resolution = load("schemas/factory/factory-resolution.schema.json")
    capability = load("schemas/capability/capability-draft.schema.json")

    capability_types = request["properties"]["preferred_capability_type"]["enum"]
    decisions = response["properties"]["decision"]["enum"]
    risks = capability["properties"]["risk_level"]["enum"]
    availability = catalog["properties"]["availability"]["enum"]
    configuration = catalog["properties"]["configuration_status"]["enum"]
    readiness = resolution["properties"]["activation_readiness"]["enum"]

    return rf'''// Generated by scripts/generate_typescript.py. DO NOT EDIT.
// Source of truth: alos-contracts JSON Schemas and public OpenAPI.

export const FACTORY_ANALYZE_PATH = "/api/v1/genesis/factory/analyze" as const;

export type CapabilityType = {union(capability_types)};
export type FactoryDecision = {union(decisions)};
export type RiskLevel = {union(risks)};
export type CapabilityAvailability = {union(availability)};
export type CapabilityConfigurationStatus = {union(configuration)};
export type ActivationReadiness = {union(readiness)};

export interface FactoryAnalyzeRequest {{
  readonly requirement: string;
  readonly preferred_capability_type?: CapabilityType;
}}

export interface CapabilityCatalogItem {{
  readonly capability_id: string;
  readonly version: string;
  readonly name: string;
  readonly purpose: string;
  readonly capability_type: CapabilityType;
  readonly risk_level: RiskLevel;
  readonly availability: CapabilityAvailability;
  readonly configuration_status: CapabilityConfigurationStatus;
  readonly backing_tool_ids: readonly string[];
  readonly permission_refs: readonly string[];
  readonly scope_refs: readonly string[];
  readonly keywords?: readonly string[];
}}

export interface CapabilityDraft {{
  readonly tenant_id: string;
  readonly organization_id: string;
  readonly workspace_id: string;
  readonly correlation_id: string;
  readonly capability_id: string;
  readonly version: string;
  readonly name: string;
  readonly purpose: string;
  readonly owner: string;
  readonly capability_type: CapabilityType;
  readonly output_state: "DRAFT";
  readonly lifecycle_state: "DRAFT";
  readonly scope_refs: readonly string[];
  readonly tool_ids: readonly string[];
  readonly permission_refs: readonly string[];
  readonly prohibited_actions: readonly string[];
  readonly risk_level: RiskLevel;
  readonly evidence_requirements: readonly string[];
  readonly test_requirements: readonly string[];
  readonly constraints?: readonly string[];
}}

export interface AgentDraft {{
  readonly draft_id: string;
  readonly tenant_id: string;
  readonly organization_id: string;
  readonly workspace_id: string;
  readonly correlation_id: string;
  readonly agent_id: string;
  readonly version: string;
  readonly purpose: string;
  readonly capability_type: "AGENT";
  readonly scope_refs: readonly string[];
  readonly tool_ids: readonly string[];
  readonly permission_refs: readonly string[];
  readonly prohibited_actions: readonly string[];
  readonly risk_level: RiskLevel;
  readonly evidence_requirements: readonly string[];
  readonly test_requirements: readonly string[];
  readonly lifecycle_state: "DRAFT";
  readonly agent_definition: Readonly<Record<string, unknown>>;
}}

export interface RegistryDraftReference {{
  readonly subject_type: "CAPABILITY" | "AGENT";
  readonly identifier: string;
  readonly version: string;
  readonly state: "DRAFT";
}}

export interface RegistryDraftResult {{
  readonly state: "DRAFT";
  readonly registered_refs: readonly RegistryDraftReference[];
}}

export interface FactoryAnalyzeResponse {{
  readonly correlation_id: string;
  readonly decision: FactoryDecision;
  readonly reason: string;
  readonly existing_capability_refs: readonly CapabilityCatalogItem[];
  readonly capability_draft: CapabilityDraft | null;
  readonly agent_draft: AgentDraft | null;
  readonly registry_result: RegistryDraftResult | null;
}}

export interface ContractError {{
  readonly code: string;
  readonly message: string;
  readonly details?: Readonly<Record<string, unknown>>;
  readonly correlation_id: string;
  readonly retryable: boolean;
}}

export class AlosContractError extends Error {{
  readonly problem: ContractError;

  constructor(problem: ContractError) {{
    super(problem.message);
    this.name = "AlosContractError";
    this.problem = problem;
  }}
}}

export async function analyzeFactory(
  baseUrl: string,
  request: FactoryAnalyzeRequest,
  init: Omit<RequestInit, "body" | "method"> = {{}},
  fetcher: typeof fetch = fetch,
): Promise<FactoryAnalyzeResponse> {{
  const response = await fetcher(`${{baseUrl.replace(/\/$/, "")}}${{FACTORY_ANALYZE_PATH}}`, {{
    ...init,
    method: "POST",
    headers: {{
      Accept: "application/json",
      "Content-Type": "application/json",
      ...init.headers,
    }},
    body: JSON.stringify(request),
  }});
  const payload: unknown = await response.json();
  if (!response.ok) throw new AlosContractError(payload as ContractError);
  return payload as FactoryAnalyzeResponse;
}}
'''


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != expected:
            raise SystemExit("generated/typescript/factory.ts is stale; run the generator")
        print(f"Verified {OUTPUT.relative_to(ROOT)}")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(expected, encoding="utf-8", newline="\n")
    print(f"Generated {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
