"""Render Shared Work types directly from the canonical JSON Schema."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMA = ROOT / "schemas" / "shared-work" / "shared-work.schema.json"


def definitions() -> dict[str, dict]:
    return json.loads(SCHEMA.read_text(encoding="utf-8"))["$defs"]


def _type(property_schema: dict, *, python: bool) -> str:
    reference = property_schema.get("$ref")
    if reference:
        if reference.endswith("data-classification.schema.json"):
            return "SharedWorkDataClassification"
        if "/common/identifiers.schema.json" in reference:
            return "str" if python else "string"
        return "SharedWork" + reference.rsplit("/", 1)[-1]
    if "anyOf" in property_schema:
        return " | ".join(_type(item, python=python) for item in property_schema["anyOf"])
    if "oneOf" in property_schema:
        return " | ".join(_type(item, python=python) for item in property_schema["oneOf"])
    kind = property_schema["type"]
    if isinstance(kind, list):
        return " | ".join(_type({"type": item}, python=python) for item in kind)
    if kind == "array":
        item = _type(property_schema["items"], python=python)
        return f"list[{item}]" if python else f"readonly {item}[]"
    if kind == "object":
        return "dict[str, object]" if python else "Readonly<Record<string, unknown>>"
    return {
        "string": "str" if python else "string",
        "integer": "int" if python else "number",
        "number": "float" if python else "number",
        "boolean": "bool" if python else "boolean",
        "null": "None" if python else "null",
    }[kind]


def render_typescript() -> str:
    lines = [
        "// Generated by scripts/generate_typescript.py. DO NOT EDIT.",
        "// Source of truth: schemas/shared-work/shared-work.schema.json.",
        "",
    ]
    defs = definitions()
    classification = json.loads(
        (ROOT / "schemas" / "common" / "data-classification.schema.json").read_text(
            encoding="utf-8"
        )
    )["enum"]
    lines.append(
        "export type SharedWorkDataClassification = "
        + " | ".join(json.dumps(item) for item in classification)
        + ";"
    )
    for name, schema in defs.items():
        exported = "SharedWork" + name
        if schema["type"] == "string":
            lines.append(
                f"export type {exported} = "
                + " | ".join(json.dumps(item) for item in schema["enum"])
                + ";"
            )
            continue
        lines.append("")
        lines.append(f"export interface {exported} {{")
        required = set(schema["required"])
        for field, field_schema in schema["properties"].items():
            optional = "" if field in required else "?"
            lines.append(
                f"  readonly {field}{optional}: {_type(field_schema, python=False)};"
            )
        lines.append("}")
    return "\n".join(lines) + "\n"


def render_python() -> str:
    lines = [
        "# Generated by scripts/generate_python.py. DO NOT EDIT.",
        "# Source of truth: schemas/shared-work/shared-work.schema.json.",
        "",
        "from typing import Literal, Required, TypedDict",
        "",
    ]
    defs = definitions()
    classification = json.loads(
        (ROOT / "schemas" / "common" / "data-classification.schema.json").read_text(
            encoding="utf-8"
        )
    )["enum"]
    lines.append(
        "SharedWorkDataClassification = Literal["
        + ", ".join(repr(item) for item in classification)
        + "]"
    )
    for name, schema in defs.items():
        exported = "SharedWork" + name
        lines.append("")
        if schema["type"] == "string":
            lines.append(
                f"{exported} = Literal["
                + ", ".join(repr(item) for item in schema["enum"])
                + "]"
            )
            continue
        lines.append(f"class {exported}(TypedDict, total=False):")
        required = set(schema["required"])
        for field, field_schema in schema["properties"].items():
            value = _type(field_schema, python=True)
            if field in required:
                value = f"Required[{value}]"
            lines.append(f"    {field}: {value}")
    return "\n".join(lines) + "\n"
